import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:turo_app/mentee-onboarding/provider_storage/storage.dart';

/// Service for persisting mentee onboarding data to Firestore.
///
/// Collection: `mentee_onboarding`
/// Document ID: Auto-generated by Firestore (or you can pass a custom ID/userId).
///
/// For feature development without user login, we auto-generate a document ID.
/// Once you add authentication, pass the user's UID as the document ID to link
/// the onboarding data to the user account.
class MenteeOnboardingService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Saves the onboarding data from [provider] to Firestore.
  ///
  /// Returns the document ID of the newly created record.
  ///
  /// [userId] is optional. If provided, it will be used as the document ID.
  /// If null, Firestore auto-generates a unique ID.
  ///
  /// Throws [FirebaseException] if the write fails.
  Future<String> saveMenteeOnboarding(
    MenteeOnboardingProvider provider, {
    String? userId,
  }) async {
    // Prepare the data map from the provider
    final data = {
      'fullName': provider.fullName,
      'birthMonth': provider.birthMonth,
      'birthDay': provider.birthDay,
      'birthYear': provider.birthYear,
      'bio': provider.bio,
      'address': provider.address,
      'addressDetails': provider.addressDetails,
      'interests': provider.selectedInterests.toList(),
      'goals': provider.selectedGoals.toList(),
      'duration': provider.selectedDuration,
      'minBudget': provider.minBudget,
      'maxBudget': provider.maxBudget,
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    };

    // If userId is provided, use it as the document ID; otherwise auto-generate
    if (userId != null && userId.isNotEmpty) {
      await _firestore
          .collection('mentee_onboarding')
          .doc(userId)
          .set(data, SetOptions(merge: true));
      return userId;
    } else {
      final docRef = await _firestore.collection('mentee_onboarding').add(data);
      return docRef.id;
    }
  }

  /// Optional: Retrieve a mentee onboarding record by document ID.
  ///
  /// Returns a map of the data, or null if the document doesn't exist.
  Future<Map<String, dynamic>?> getMenteeOnboarding(String docId) async {
    final doc = await _firestore
        .collection('mentee_onboarding')
        .doc(docId)
        .get();
    return doc.exists ? doc.data() : null;
  }

  /// Optional: Stream all mentee onboarding records (useful for admin dashboards).
  ///
  /// Returns a stream of all documents in the collection.
  Stream<List<Map<String, dynamic>>> streamAllMenteeOnboarding() {
    return _firestore
        .collection('mentee_onboarding')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => {...doc.data(), 'id': doc.id})
              .toList(),
        );
  }
}
