// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiitpbj5b8X2EshowHpw6Y2YFLOalYFDo',
    appId: '1:507188440079:web:f298f35054b66ca543877a',
    messagingSenderId: '507188440079',
    projectId: 'turo-31805',
    authDomain: 'turo-31805.firebaseapp.com',
    storageBucket: 'turo-31805.firebasestorage.app',
    measurementId: 'G-0EXR6DYXLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEcR_OvwA9JP2hwY8PqD5Jxa3FTTm8pA',
    appId: '1:507188440079:android:8160d7ace74d945143877a',
    messagingSenderId: '507188440079',
    projectId: 'turo-31805',
    storageBucket: 'turo-31805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaCyu0ygqSHir-D0r8Kb5iE5RN-X0_Dg',
    appId: '1:507188440079:ios:7d2356826a8c28ce43877a',
    messagingSenderId: '507188440079',
    projectId: 'turo-31805',
    storageBucket: 'turo-31805.firebasestorage.app',
    iosBundleId: 'com.example.turo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaCyu0ygqSHir-D0r8Kb5iE5RN-X0_Dg',
    appId: '1:507188440079:ios:7d2356826a8c28ce43877a',
    messagingSenderId: '507188440079',
    projectId: 'turo-31805',
    storageBucket: 'turo-31805.firebasestorage.app',
    iosBundleId: 'com.example.turo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiitpbj5b8X2EshowHpw6Y2YFLOalYFDo',
    appId: '1:507188440079:web:69e7441df2a8871643877a',
    messagingSenderId: '507188440079',
    projectId: 'turo-31805',
    authDomain: 'turo-31805.firebaseapp.com',
    storageBucket: 'turo-31805.firebasestorage.app',
    measurementId: 'G-BCJ4K1BVPH',
  );
}
