import 'package:flutter/material.dart';
import 'screens/auth_gate.dart';
// 1. IMPORT FIREBASE LIBS
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was generated by the FlutterFire CLI

// Import your starting screen
//import 'screens/my_profile_screen.dart';

// 2. MAKE YOUR MAIN FUNCTION ASYNC
void main() async {
  // 3. ENSURE FLUTTER IS INITIALIZED
  WidgetsFlutterBinding.ensureInitialized();

  // 4. INITIALIZE FIREBASE
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 5. Run your app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Turo App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1B4D44)),
        useMaterial3: true,
      ),
      // MyProfileScreen remains the starting point
      home: const AuthGate(),
    );
  }
}

